name: nn
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.7
  shared_preferences: ^2.2.2
  path_provider: ^2.0.15
  permission_handler: ^11.3.0
  camera: ^0.11.1  # ✅ إضافة مكتبة الكاميرا
  http: ^1.4.0
  animated_text_kit: ^4.2.2
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true
